# Generated by Django 5.2.5 on 2025-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0006_alter_produto_preco_marketing_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variacao",
            options={"verbose_name": "Variação", "verbose_name_plural": "Variações"},
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing",
            field=models.FloatField(verbose_name="Preço"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("V", "Variável"), ("S", "Simples")], default="V", max_length=1
            ),
        ),
    ]
