# Generated by Django 5.2.5 on 2025-08-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="qtd_total",
            field=models.IntegerField(default=0),
        ),
    ]
